#!/bin/bash

if [ $# -lt 2 ]; then
	echo "Usage: ooogrep PATTERN FILE [FILES...]"
	exit 1
fi

PATTERN=$1
shift
FILES=("$@")

for FILE in "${FILES[@]}"; do
	unzip -p -- "$FILE" content.xml 2> /dev/null \
	| xmllint --format - 2> /dev/null \
	| grep -- "$PATTERN" | while read L; do
		echo "$FILE: $L"
	done
done
